# Generated by Django 5.2.5 on 2025-08-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_author_blog2_blog_tagline_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
